### ISSUE TITLE
bb2 mac address and IP reset every time in zerotier 

### ISSUE THREAD

**Issue by fuleinist** [uavpal/beboptwo4g#12]
After softmod installed. My bb2 always reset it's mac address once it's connected to 4g. So I  have to get back to my ZT network and config it's new profile and assign a new IP before each flight.

**Comment by s0ftice** [comment]
the MAC address of which interface? never seen that. zerotier picks up the member ID from the local directory, it's not MAC dependent.

what is a new profile? where do you assign a new IP? that's not necessary.

**Comment by fuleinist** [comment]
I am not sure what interface of the mac address come from but most likely from the 4g dongle connected to bb2.

a new profile as a new member in the network. instead of re-activating the old member bb2 was on last time. It creates a new member and thus I have to tick the boxes to allow auth and ethernet bridging again.

**Comment by s0ftice** [comment]
Can you check if you have no disk space left on your BB2? Maybe that's why the member information gets regenerated as it is not able to store it...?

**Comment by fuleinist** [comment]
Confirmed that I have disk space on my BB2 unit. Tested a few more times and the issue still persisted.

Tested on my disco unit with exact same 4g USB hardware under the same zero tier network without any issue.

Both sky controllers 2 and disco drone will re-register themselves as the same member. only BB2 unit keep register as a new member.

**Comment by s0ftice** [comment]
what firmware version are you running on your Bebop 2?

**Comment by fuleinist** [comment]
4.7.1

**Comment by fuleinist** [comment]
quick update: I created another network only for bb2 and it seems has fixed the problem. Will test it this week and confirm the fix. Cheers

**Comment by fuleinist** [comment]
Confirmed issue resolved by moving devices into separate network. Closing issue now.
