### ISSUE TITLE
Return to home dosent work

### ISSUE THREAD

**Issue by vedmakV** [uavpal/beboptwo4g#13]
Hello

I have a BB2 Power edition and all work well but the RTH dosent work. The drone go at an alititude to 2 meters from the ground and do nothing more.

Exemple : I go to a church from my home ~1 km I push RTH and the drone dont come  back and go to 2 meters altitude...

Maybe I do something bad or I need to install the prog again ? 

Thanks for your futur help !

**Comment by s0ftice** [comment]
Hi vedmakV

This behavior only happened on 4G or also on Wi-Fi?
Did it only happen once or repeatedly?

To be honest, never heard of that.

**Comment by vedmakV** [comment]
It happen on WI-FI and 4G. It's everytime when I use BTH he come back just in altitude. Maybe I shoud reinstall them? Cordially-------- Message original --------Objet : Re: [uavpal/beboptwo4g] Return to home dosent work (#13)De : SoftIce À : uavpal/beboptwo4g Cc : vedmakV ,Author Hi vedmakV
This behavior only happened on 4G or also on Wi-Fi?
Did it only happen once or repeatedly?
To be honest, never heard of that.

**Comment by s0ftice** [comment]
This is hardly related to the softmod. So I don't think reinstalling will help

**Comment by vedmakV** [comment]
HummmSo I need to do what? Because everything work well but not the important one-------- Message original --------Objet : Re: [uavpal/beboptwo4g] Return to home dosent work (#13)De : SoftIce À : uavpal/beboptwo4g Cc : vedmakV ,Author This is hardly related to the softmod. So I don't think reinstalling will help

**Comment by s0ftice** [comment]
did RTH work fine before you installed the softmod? you can try to remove it again and see if RTH works then. As said, I can't imagine that this issue is related to the softmod. Nobody else reported this issue so far (the Bebop2 softmod has a few thousand downloads the last 12 months)

**Comment by vedmakV** [comment]
Yes the RTH work well before, I used it a lot of time before. I will try to remove then and I recontact you if the problem come back. #I know maybe a PB2 power change something? Cordially-------- Message original --------Objet : Re: [uavpal/beboptwo4g] Return to home dosent work (#13)De : SoftIce À : uavpal/beboptwo4g Cc : vedmakV ,Author did RTH work fine before you installed the softmod? you can try to remove it again and see if RTH works then. As said, I can't imagine that this issue is related to the softmod. Nobody else reported this issue so far (the Bebop2 softmod has a few thousand downloads the last 12 months)

**Comment by s0ftice** [comment]
No, the Power version is running the same Parrot firmware.
Give it a try and remove: https://uavpal.com/bebop2/wiki/Removing-the-softmod

**Comment by vedmakV** [comment]
Ok, I try this tomorrow and I intsall it again. Then, I test RTH if this work or not.
Maybe there is a folder with error or anything inside the drone that I can send to you for finding the problem if him still?

**Comment by s0ftice** [comment]
any luck?

you can try this: https://uavpal.com/bebop2/faq#debug

**Comment by vedmakV** [comment]
Yes, i try again and now work well. Problem solve! Thanks
