### ISSUE TITLE
Bebop2 change the automatic return altitude

### ISSUE THREAD

**Issue by yep877** [uavpal/beboptwo4g#14]
How to change the height of automatic return from 20 meters to 100 meters?Who can change in firmware? Please contact me at lianyeping@163.com , I am willing to pay.

**Comment by s0ftice** [comment]
Hi,
It can be done up to firmware version 4.2.1 by changing `heightToReturnHome` in `/etc/colibry/milosboard/reference.cfg`.

Have a look here for Bebop 2 firmwares: https://github.com/uavpal/beboptwo4g/wiki/Manual-firmware-upgrade-and-downgrade-of-Parrot-Bebop-2

I'll close this issue, as it's not 4G softmod relarted.
Feel free to join our community on Slack: https://uavpal.com/slack to discuss all kind of modifications for the Disco and Bebop 2.

SoftIce
