### ISSUE TITLE
bebop2,How to Change the Cutoff Voltage

### ISSUE THREAD

**Issue by yep877** [uavpal/beboptwo4g#15]
When the aircraft lands automatically, the voltage measured at this time is about 10.6 volts.How to change the airplane code to 8.2 volts.So we can use 18650 batteries.Ask developers or experts to give answers.Thank you very much in advance.

**Comment by s0ftice** [comment]
I suggest to discuss this on our Slack workspace https://uavpal.com/slack
I close the issue hereby, as it's not 4G softmod related.
