### ISSUE TITLE
Bebop2  Can the firmware of version 4.4 be changed to 4G?

### ISSUE THREAD

**Issue by yep877** [uavpal/beboptwo4g#16]
Firmware4.4.0edition Although older, it is possible to change the cut-off voltage within the system. I would like to ask, is it possible to use this version to change 4G flight?

**Comment by s0ftice** [comment]
Unfortunately no, the supported firmware versions by the 4G softmod are 4.4.2 to 4.7.1

**Comment by OpenUAS** [comment]
Close the issue maybe?
