### ISSUE TITLE
Manual firmware update help 

### ISSUE THREAD

**Issue by Antho029** [uavpal/beboptwo4g#17]
Hi, 

I've maybe a problem with my firmware, when i try to connect my drone to my phone app FreeFlight, i don't see my drone.

Whereas my drone's wifi is connected, i don't understand what is the issues. So i tried to restore to another firmware.

They are already stored to "Internal_000" folder, the next step : launch the install with Putty but what command write ?

Thanks You

**Comment by s0ftice** [comment]
Are you talking about Parrot firmware or the 4G softmod?

**Comment by Antho029** [comment]
Hi, 

I'm talking about Parrot Firmware.

Thx

**Comment by s0ftice** [comment]
What you need is described here https://uavpal.com/bebop2/wiki/Manual-firmware-upgrade-and-downgrade-of-Parrot-Bebop-2

Github issues are meant for feedback on the softmod. Please contact Parrot if you need help with connecting to your drone.
