### ISSUE TITLE
Bebop and Glympse

### ISSUE THREAD

**Issue by Slickster4** [uavpal/beboptwo4g#18]
I have a bebop drone with Skycontroller 2P. I use my apple 11xr iphone for both the personal hotspot and freeflight pro app and Glympse app using the 4G mod. The modem is Huawei E3372 510 on an ATT network; the iphone is also on ATT. The glympse tracks the iphone and not the drone.
The number I used on the Glympse app is the iphone number; the phone number associated with the modem is a different number. For the modem I am using data only service. The freeflight pro seems to work OK but not the glympse app. Should I use the number associated with Modem instead of the iphone number? Will the glympse work with a data only service on the modem?

**Comment by s0ftice** [comment]
Reason why the drone is not shown under the Glympse link is usually a wrong Glympse API key entered in the config file.

The number you used to sign up for the Glympse account is irrelevant.
The only number that counts is in the config file phonenumber, that's where you want to receive the SMS with the Glympse link. So it should NOT be the number of the SIM card in the modem for obvious reasons.

**Comment by OpenUAS** [comment]
@Slickster4, did it work out for you?, if so issue can be closed.
