### ISSUE TITLE
Video recorded on the microsd card two strange files.

### ISSUE THREAD

**Issue by raasq** [uavpal/beboptwo4g#19]
Hi, I have a question, why after removing the card from the modem there is no normal .mp4 file, but only two files (Bebop_2_2021-07-07T205726 + 0200_E01BF0.mp4-encaps.dat) and (Bebop_2_2021-07-07T205726 + 0200_E01BF0.-encaps.tmp) where the 1 is 505 KB and the other 2 GB. I have tried everything and nothing recognizes the video.
I am counting on some help :(

**Comment by s0ftice** [comment]
That can happen if you remove the card while the video is still being recorded.

There are tools to fix such files.

**Comment by raasq** [comment]
But I had no way to get the card out of the modem during the flight, anyway I landed without any problems and pulled out the card at home.  And recovery programs unfortunately are paid...  The topic can be closed, the easiest way out is to fly again :)

**Comment by s0ftice** [comment]
It could also be that the USB cable became loose and lost physical connection for a second.
There is a free Windows tool, just can't remember the name.
