### ISSUE TITLE
glympse/pushbullet not sending link

### ISSUE THREAD

**Issue by highwind001** [uavpal/beboptwo4g#2]
Successfully installed and flew soft moded bebop 2 using sky controller 2. However no luck with getting glympse/pushbullet to work. I had created accounts for both and entered the correct API key for glympse and created access token for pushbullet. I had read the FQA section and tried adding or omitting  "+" or "1" to the config/phonenumber, no success. Do you guys have any other suggestions I can try for this issue. Your help will be greatly appreciated. Thank you.

**Comment by mtony61** [comment]
hello, check that there is no space when you copy / paste for the glym identity,

on the other hand, I have a disco and everything works correctly, already fly in 4G and do 15km

on the other hand on the bebop, with the same key and uavpal / bebop2 files, key 4g does not work, it flashes my steps, is this normal? how did you do it, did you modify the UAVPAL files
 thank you for your help

**Comment by highwind001** [comment]
Hi, checked, no spacing for copied and paste glympse key. If modem SIM card is in a phone it can receive and send links. I might try creating a different key.
Per your question, I didnt do any modification on the files. Just uploaded it into "/internal_000" with my infos.
The controlls and video stream are very good with minimal lag. Drone SIM card carrier is verizon, phone is at&t.

**Comment by highwind001** [comment]
Update: drone sending link to phone but not sharing gps location. Tried putting drone sim in another phone, shared location to my other phone, then transfered the sim into drone(usb modem); still a no go.
