### ISSUE TITLE
Glympse Problem

### ISSUE THREAD

**Issue by Jujuleprince** [uavpal/beboptwo4g#20]
Hello from France, 
I'm sorry for the translation in advance. I installed 4G on my Bebop 2 Power and it works perfectly well and I thank you for it. However, I cannot get Glympse to work on my Iphone 11. I receive a link from Pushbullet via Chrome with only ::
(Bebop2Power-000000's GPS location for information 
You can track the location of your Bebop2Power-000000 here: https://glympse.com/)

I updated the uavpal_glympse.sh file.
My problem being that I am not receiving any position link from my bebop. 

Can you help me please ?

Best regards

**Comment by Jujuleprince** [comment]
Problem solved ! Thank you

**Comment by stain302000** [comment]
Bonjour Jujuleprince,
J'ai exactement le même problème que vous pour récupérer le lien complet de GLYMPSE.
Tout fonctionne a merveille a part cela !
Comment avez vous fait pour régler ce problème?.
merci d'avance.
Fabrice

**Comment by s0ftice** [comment]
See #88 (https://github.com/uavpal/disco4g/issues/88)
