### ISSUE TITLE
skycontroller doesn't connect to hotspot

### ISSUE THREAD

**Issue by highwind001** [uavpal/beboptwo4g#3]
Hi, 
Updated files to my bb2 and sc2. Glympse now works. But my skycontroller doesn't connect to my hotspot. SSID, WPA and Zero tier ID have been verified to be correct. BB2 connects to Zero tier without any problems. Any help would be appreciated. Thank you.

**Comment by uavpal** [comment]
what LED color do you see when double pressing the Settings button on SC2?

**Comment by highwind001** [comment]
USB modem stopped working when plugged into the bb2. Does not even light up at all. Works fine when plugged into my laptop. Im at a dead end for this.

**Comment by uavpal** [comment]
did you upgrade the BB2 firmware? if so, you need to reinstall the softmod.

**Comment by highwind001** [comment]
Reinstalled softmod, usb modem working once again, bb2 connecting to zerotier. But sc2 still does not connect. From green, flashes purple, red, then back to green again. Thank you for your help.

**Comment by uavpal** [comment]
That means it can’t connect to your mobile hotspot.

Did you see this? https://uavpal.com/disco/faq#wififail
