### ISSUE TITLE
Sc2 not going green

### ISSUE THREAD

**Issue by davebooma** [uavpal/beboptwo4g#4]
Hi all I have installed and reinstalled the mod and no matter what I do I can't get the led to
 Blue

**Comment by davebooma** [comment]
I have 2 sc2 and neither will do it, and zeroteir also doesn't show it although my bb2 seems to be just fine.
I am pressing the settings button twice although while on filezilla I did get a message saying "not supported in ftp so passwords may be sent in clearcode" if that has anything to do with it...please help and Thankyou for your continued support,
Dave

**Comment by uavpal** [comment]
Hi Dave, if your problem still persists, can you upload a screenshot on Slack? Thanks
SoftIce

**Comment by uavpal** [comment]
Dave, can I close this? All solved?

**Comment by davebooma** [comment]
No matter what I do softice it's just not happening I need the sc2 refreshing as I put the sc2p mod on which is different but even still the sc2p won't recognise and for some reason the 4g dongle isn't lighting up in bebop 2 now despite a new otg cable, I really want this to work.

**Comment by uavpal** [comment]
Need some more information here on the current status.
SC2 and Modem: LED color/state (flashing/solid). What works / what not, e.g. Dongle on PC, etc.

**Comment by s0ftice** [comment]
Dave, I'm going to close it. Please ask on Slack if you still need help.
Thanks, SoftIce
