### ISSUE TITLE
can't find new members on zerotier network

### ISSUE THREAD

**Issue by chansuny** [uavpal/beboptwo4g#7]
i did everything what i read in this site and finally find out zerotier doesn't work... please help me. i want to fly with LTE connetion and fly far more than 1.5kms

**Comment by s0ftice** [comment]
that usually happens when you change the network id without entirely removing the softmod first.

feel free to join us in Slack: https://uavpal.com/slack will be able to help you in there.
SoftIce

**Comment by s0ftice** [comment]
can I close this?

**Comment by davebooma** [comment]
Sorry softice, it's Xmas and work us really busy, I've had no luck whatsoever so going to give up and put it down as a lost cause mate, thanks for the support you've given, it's greatly appreciated.
Regards
Dave

Sent from my Sony Xperia™ smartphone

---- SoftIce wrote ----


can I close this?

**Comment by s0ftice** [comment]
Sure. Feel free to come back to our Slack channel once you have time. We'll try to assist/support your setup.
SoftIce

**Comment by chansuny** [comment]
softice, do u mean to delete all of softmod from bebop2 by filezilla? or is there any other method to delete softmod? i still can't enjoy lte flying...

**Comment by s0ftice** [comment]
https://github.com/uavpal/beboptwo4g/wiki/Removing-the-softmod

Join us on Slack and we will try to troubleshoot your setup.
SoftIce

**Comment by davebooma** [comment]
Hi softice.
I have just received your email regarding the current updates and improvements and notices the code update for sc2p.
As you may remember I had huge problems trying to sync the sc2p.
Can you confirm that I can now use the 2p and is there a YouTube tutorial for this as there is with the standard S.C.
many kind regards and thanks for the update.
Dave Beaumont.

Get Outlook for Android<https://aka.ms/ghei36>

Get Outlook for Android<https://aka.ms/ghei36>


Get Outlook for Android<https://aka.ms/ghei36>

**Comment by s0ftice** [comment]
Yes, give it a try. Just download and install the latest version. The youtube walkthroughs apply to SC2 and SC2P. It's also the same .zip archive for both. Visit us on Slack if you need help! :)
